site_name: ScoreKeeper Plugin
pages:
  - 'Introduction': 'index.md'
  - 'API': 'api.md'
  - 'Encryption': 'encrypt.md'
  - 'Demo Project': 'demo.md'
  - 'About': 'about.md'
copyright: "&copy;2018 C. Byerley - develephant.com"
theme: readthedocs
extra_css:
  - css/extra.css
  - css/friendly.css
site_url: https://develephant.github.io/scorekeeper-plugin
site_dir: ../docs
markdown_extensions:
  - admonition
  - codehilite